version: 2

updates:
  - directory: "/"

    package-ecosystem: github-actions

    schedule:
      interval: daily

    target-branch: main

  - directory: "/"

    package-ecosystem: mix

    schedule:
      interval: daily

    target-branch: main
