name: ci

on: push

jobs:
  dialyzer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2

        with:
          key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}

          path: _build

      - uses: erlef/setup-elixir@v1

        with:
          elixir-version: ${{ matrix.elixir }}

          otp-version: ${{ matrix.otp }}

      - run: mix deps.get

      - run: mix dialyzer

    strategy:
      matrix:
        elixir:
          - 1.12.x
          - 1.13.x
          - 1.14.x

        exclude:
          - elixir: 1.12.x

            otp: 25.x

        otp:
          - 23.x
          - 24.x
          - 25.x

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2

        with:
          key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}

          path: _build

      - uses: erlef/setup-elixir@v1

        with:
          elixir-version: ${{ matrix.elixir }}

          otp-version: ${{ matrix.otp }}

      - run: mix deps.get

      - run: mix test

    strategy:
      matrix:
        elixir:
          - 1.12.x
          - 1.13.x
          - 1.14.x

        exclude:
          - elixir: 1.12.x

            otp: 25.x

        otp:
          - 23.x
          - 24.x
          - 25.x
