name: ci

on: push

jobs:
    dialyzer:
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - uses: actions/cache@v3

              with:
                  key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}

                  path: |
                      _build
                      deps

            - uses: erlef/setup-beam@v1

              with:
                  elixir-version: ${{ matrix.elixir }}

                  otp-version: ${{ matrix.erlang }}

            - run: mix deps.get

            - run: mix compile --warnings-as-errors

            - run: mix dialyzer --format github

            - run: rm -rf _build/dev/lib/postscript

        strategy:
            matrix:
                include:
                    - elixir: 1.10.x

                      erlang: 21.x

                      os: ubuntu-20.04

                    - elixir: 1.10.x

                      erlang: 22.x

                      os: ubuntu-20.04

                    - elixir: 1.11.x

                      erlang: 21.x

                      os: ubuntu-20.04

                    - elixir: 1.11.x

                      erlang: 22.x

                      os: ubuntu-20.04

                    - elixir: 1.11.x

                      erlang: 23.x

                      os: ubuntu-20.04

                    - elixir: 1.12.x

                      erlang: 22.x

                      os: ubuntu-20.04

                    - elixir: 1.12.x

                      erlang: 23.x

                      os: ubuntu-20.04

                    - elixir: 1.12.x

                      erlang: 24.x

                      os: ubuntu-22.04

                    - elixir: 1.13.x

                      erlang: 22.x

                      os: ubuntu-20.04

                    - elixir: 1.13.x

                      erlang: 23.x

                      os: ubuntu-20.04

                    - elixir: 1.13.x

                      erlang: 24.x

                      os: ubuntu-22.04

                    - elixir: 1.14.x

                      erlang: 23.x

                      os: ubuntu-20.04

                    - elixir: 1.14.x

                      erlang: 24.x

                      os: ubuntu-22.04

                    - elixir: 1.14.x

                      erlang: 25.x

                      os: ubuntu-22.04

    test:
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - uses: actions/cache@v3

              with:
                  key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}

                  path: |
                      _build
                      deps

            - uses: erlef/setup-beam@v1

              with:
                  elixir-version: ${{ matrix.elixir }}

                  otp-version: ${{ matrix.erlang }}

            - run: mix deps.get

            - run: MIX_ENV=test mix compile --warnings-as-errors

            - run: mix test

            - run: rm -rf _build/test/lib/postscript

        strategy:
            matrix:
                include:
                    - elixir: 1.10.x

                      erlang: 21.x

                      os: ubuntu-20.04

                    - elixir: 1.10.x

                      erlang: 22.x

                      os: ubuntu-20.04

                    - elixir: 1.11.x

                      erlang: 21.x

                      os: ubuntu-20.04

                    - elixir: 1.11.x

                      erlang: 22.x

                      os: ubuntu-20.04

                    - elixir: 1.11.x

                      erlang: 23.x

                      os: ubuntu-20.04

                    - elixir: 1.12.x

                      erlang: 22.x

                      os: ubuntu-20.04

                    - elixir: 1.12.x

                      erlang: 23.x

                      os: ubuntu-20.04

                    - elixir: 1.12.x

                      erlang: 24.x

                      os: ubuntu-22.04

                    - elixir: 1.13.x

                      erlang: 22.x

                      os: ubuntu-20.04

                    - elixir: 1.13.x

                      erlang: 23.x

                      os: ubuntu-20.04

                    - elixir: 1.13.x

                      erlang: 24.x

                      os: ubuntu-22.04

                    - elixir: 1.14.x

                      erlang: 23.x

                      os: ubuntu-20.04

                    - elixir: 1.14.x

                      erlang: 24.x

                      os: ubuntu-22.04

                    - elixir: 1.14.x

                      erlang: 25.x

                      os: ubuntu-22.04
